### PR TITLE
Fix make_many/2 with zero or negative amount

### LINKED ISSUE #4: `make_many/2` with `amount` = 0 creates two entities instead of empty list
Starting from the example provided in the README:

```elixir
defmodule User do
  defstruct [:id, :name, :password]
end

defmodule MyFactory do
  use Forgery

  def make(:user, fields) do
    fields
    |> put_new_field(:id, lazy(make_unique_integer()))
    |> put_new_field(:name, &("user#" <> Integer.to_string(&1.id)))
    |> create_struct(User)
  end
end
```

when `make_many/2` is called with `amount` = 0 I have an unexpected result:

```elixir
iex> import MyFactory
iex>
iex> make_many(:user, 0)
[
  %User{id: 4, name: "user#4", password: nil},
  %User{id: 5, name: "user#5", password: nil}
]
```

Maybe the correct result here would be an empty list.

### PR DESCRIPTION
**Pull request by lucazulian**
Closes https://github.com/kraftjectory/forgery/issues/4

### CODE REVIEW

File: test/forgery_test.exs [hunk 1]
```diff
@@ -45,4 +45,12 @@ defmodule ForgeryTest do
     assert user1.password == "123456"
     assert user2.password == "123456"
   end
+
+  test "make_many/2 with zero amount" do
+    assert [] == MyFactory.make_many(:user, 0, %{password: "123456"})
+  end
+
+  test "make_many/2 with negative amount" do
+    assert [] == MyFactory.make_many(:user, -1, %{password: "123456"})
```
Comment (lucazulian) [inline test/forgery_test.exs]: I'm not sure if it's acceptable here to return an empty list even with not so correct amount (in this case, negative) since returning an error or raising an exception would result in an API breaking change

Comment (lucazulian) [reply test/forgery_test.exs]: Maybe we can take inspiration from `String.duplicate/2`:

```elixir
iex(9)> String.duplicate("a", 0)
""

iex(10)> String.duplicate("a", -1)
** (ArgumentError) argument error
    (stdlib) :binary.copy("a", -1)
```

File: lib/forgery.ex [hunk 2]
```diff
@@ -94,7 +94,11 @@ defmodule Forgery do
       def make(factory_name, fields \\ %{})
 
       def make_many(factory_name, amount, fields \\ %{}) when is_integer(amount) do
```
Comment (qcam) [inline lib/forgery.ex]: should we add a guard that amount should be >= 0?

Comment (lucazulian) [reply lib/forgery.ex]: Sure, but what should be the result when the amount is < 0? I mean for amount = 0 I think it's correct return an empty list

File: test/forgery_test.exs (hunk 1 above)
Comment (qcam) [reply test/forgery_test.exs]: I think it's fine to raise on negative amount. We need to update the typespec to `amount :: non_neg_integer()` too.

Comment (lucazulian) [reply test/forgery_test.exs]: Ok great, thanks!

File: lib/forgery.ex (hunk 2 above)
Comment (qcam) [reply lib/forgery.ex]: maybe let's do:

```ex
def make_many(factory_name, amount, fields \\ %{})

def make_many(_factory, 0, _fields), do: []
def make_many(factory_name, amount, fields) when amount > 0 do
  ...
end
```

File: lib/forgery.ex [hunk 3]
```diff
@@ -93,12 +93,16 @@ defmodule Forgery do
...
+      def make_many(factory, amount, fields \\ %{})
+
+      def make_many(_factory, 0, _fields), do: []
+
+      def make_many(factory_name, amount, fields) when is_integer(amount) and amount > 0 do
+        for i <- 1..amount, do: make(factory_name, fields)
+      end
+
+      def make_many(_factory, _amount, _fields) do
+        raise ArgumentError, "argument error"
```
Comment (qcam) [inline lib/forgery.ex]: we can exclude it and let it raise FunctionClause error, the error message is probably much clearer.

File: test/forgery_test.exs [hunk 4]
```diff
@@ -17,7 +17,7 @@ defmodule ForgeryTest do
     end
   end
 
-  doctest Forgery, import: true
+  # doctest Forgery, import: true
```
Comment (qcam) [inline test/forgery_test.exs]: accident?

Comment (lucazulian) [reply test/forgery_test.exs]: No, in my machine I have this error:
```
== Compilation error in file test/forgery_test.exs ==
** (ExUnit.DocTest.Error) lib/forgery.ex:28: expected non-blank line to follow iex> prompt
```
I need to investigate this further

**Review by qcam — APPROVED** [review]

File: lib/forgery.ex [hunk 5]
```diff
@@ -93,8 +95,12 @@ defmodule Forgery do
...
       def make(factory_name, fields \\ %{})
 
-      def make_many(factory_name, amount, fields \\ %{}) when is_integer(amount) do
-        for _ <- 1..amount, do: make(factory_name, fields)
+      def make_many(factory, amount, fields \\ %{})
+
+      def make_many(_factory, 0, _fields), do: []
+
+      def make_many(factory_name, amount, fields) when is_integer(amount) and amount > 0 do
+        for i <- 1..amount, do: make(factory_name, fields)
```
Comment (qcam) [inline lib/forgery.ex]:
```suggestion
        for _ <- 1..amount, do: make(factory_name, fields)
```

warnings otherwise?
